export const allConstants = {

    ADD_PLAYER_REQUEST: 'ADD_PLAYER_REQUEST',
    ADD_PLAYER_SUCCESS: 'ADD_PLAYER_SUCCESS',
    ADD_PLAYER_FAILURE: 'ADD_PLAYER_FAILURE',

    VIEW_ALL_PLAYERS_REQUEST: 'VIEW_ALL_PLAYERS_REQUEST',
    VIEW_ALL_PLAYERS_SUCCESS: 'VIEW_ALL_PLAYERS_SUCCESS',
    VIEW_ALL_PLAYERS_FAILURE: 'VIEW_ALL_PLAYERS_FAILURE'

}
